# Generated by Django 4.2.4 on 2023-11-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minsk130school', '0002_categoriespaidservices_paidservices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='brief_information',
            field=models.TextField(default=0, verbose_name='Краткая информация'),
            preserve_default=False,
        ),
    ]
