# Generated by Django 4.2.4 on 2023-11-17 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Minsk130school', '0004_questions_alter_admissionapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionapplication',
            name='parent_contact',
            field=models.CharField(max_length=100, verbose_name='Телефон родителя'),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='parent_name',
            field=models.CharField(max_length=100, verbose_name='ФИО родителя'),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='parent_personal_data',
            field=models.CharField(max_length=150, verbose_name='Персональные данные родителя'),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='student_name',
            field=models.CharField(max_length=100, verbose_name='ФИО ученика'),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='student_personal_data',
            field=models.CharField(max_length=150, verbose_name='Персональные данные ученика'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='paid_service',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='teachers', to='Minsk130school.paidservices', verbose_name='Платные услуги'),
        ),
    ]
