# Generated by Django 4.2.4 on 2023-11-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minsk130school', '0006_administration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administration',
        ),
        migrations.AddField(
            model_name='leadershipcontacts',
            name='image',
            field=models.ImageField(default=0, upload_to='administration_images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
