# Generated by Django 4.2.4 on 2023-11-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Minsk130school', '0007_delete_administration_leadershipcontacts_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licenses',
            old_name='file',
            new_name='image',
        ),
    ]
